#[target.thumbv8m.main-none-eabihf]
#rustflags = [
#    "-C", "link-arg=-Tlink.x",

    # code optimizations.
    #"-Z", "trap-unreachable=yes",
    #"-C", "no-vectorize-loops",

    # Fixes LLVM bug on function outlining
#    "-C", "llvm-args=--enable-machine-outliner=never",
#]

#[build]
#target = "thumbv8m.main-none-eabihf"

#[profile.release]
#lto = true
#debug = true
#codegen-units = 1
#opt-level = "s"
