[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",

    # code optimizations.
    #"-Z", "trap-unreachable=yes",
    "-C", "no-vectorize-loops",
]

[build]
target = "thumbv8m.main-none-eabihf"

[profile.release]
lto = true
debug = true
codegen-units = 1
opt-level = "z"
